"""empty message

Revision ID: 18d0d788f404
Revises: 34694b56a3b7
Create Date: 2015-06-13 15:26:07.919054

"""

# revision identifiers, used by Alembic.
revision = '18d0d788f404'
down_revision = '34694b56a3b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
