"""empty message

Revision ID: 26fa526d8fd9
Revises: 36ebe369a734
Create Date: 2015-06-13 15:24:24.778656

"""

# revision identifiers, used by Alembic.
revision = '26fa526d8fd9'
down_revision = '36ebe369a734'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
