"""empty message

Revision ID: 2aa7926d78aa
Revises: 49c748b81ab0
Create Date: 2015-06-13 20:56:16.213900

"""

# revision identifiers, used by Alembic.
revision = '2aa7926d78aa'
down_revision = '49c748b81ab0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
