"""empty message

Revision ID: 34694b56a3b7
Revises: 26fa526d8fd9
Create Date: 2015-06-13 15:24:28.718369

"""

# revision identifiers, used by Alembic.
revision = '34694b56a3b7'
down_revision = '26fa526d8fd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
