"""empty message

Revision ID: 36ebe369a734
Revises: 4dd58541a185
Create Date: 2015-06-13 15:21:25.282227

"""

# revision identifiers, used by Alembic.
revision = '36ebe369a734'
down_revision = '4dd58541a185'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
