"""empty message

Revision ID: 49c748b81ab0
Revises: 1096089d177b
Create Date: 2015-06-13 15:59:20.909754

"""

# revision identifiers, used by Alembic.
revision = '49c748b81ab0'
down_revision = '1096089d177b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
